<?php


namespace amin0x\nabidh;


final class CQ extends Field
{

    /**
     * CQ constructor.
     */
    public function __construct($Quantity = '', $Units = '')
    {
    }

    /**
     * @return mixed
     */
    public function getQuantity()
    {
        return $this->getElementValue(1);
    }

    /**
     * @param mixed $Quantity
     */
    public function setQuantity($Quantity): void
    {
        $this->setElementValue(1, $Quantity);
    }

    /**
     * @return mixed
     */
    public function getUnits()
    {
        return $this->getElementValue(2);
    }

    /**
     * @param mixed $Units
     */
    public function setUnits($Units): void
    {
        $this->setElementValue(2, $Units);
    }


    public function __toString(): string
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}