<?php


namespace amin0x\nabidh;


final class CX extends Element
{

    /**
     * CX constructor.
     * @param string $IdNumber
     * @param string $AssigningAuthority
     * @param string $IdentifierTypeCode
     */
    public function __construct(string $IdNumber, string $AssigningAuthority, string $IdentifierTypeCode)
    {
        $this->setIdNumber($IdNumber);
        $this->setAssigningAuthority($AssigningAuthority);
        $this->setIdentifierTypeCode($IdentifierTypeCode);
    }

    /**
     * @return string
     */
    public function getIdNumber(): string
    {
        return $this->getElementValue(1);
    }

    /**
     * @param string $IdNumber
     */
    public function setIdNumber(string $IdNumber): void
    {
        $this->setElementValue(1, $IdNumber);
    }

    /**
     * @return string
     */
    public function getCheckDigit(): string
    {
        return $this->getElementValue(2);
    }

    /**
     * @param string $CheckDigit
     */
    public function setCheckDigit(string $CheckDigit): void
    {
        $this->setElementValue(2, $CheckDigit);
    }

    /**
     * @return string
     */
    public function getCheckDigitScheme(): string
    {
        return $this->getElementValue(3);
    }

    /**
     * @param string $CheckDigitScheme
     */
    public function setCheckDigitScheme(string $CheckDigitScheme): void
    {
        $this->setElementValue(3, $CheckDigitScheme);
    }

    /**
     * @return string
     */
    public function getAssigningAuthority(): string
    {
        return $this->getElementValue(4);
    }

    /**
     * @param string $AssigningAuthority
     */
    public function setAssigningAuthority(string $AssigningAuthority): void
    {
        $this->setElementValue(4, $AssigningAuthority);
    }

    /**
     * @return string
     */
    public function getIdentifierTypeCode(): string
    {
        return $this->getElementValue(5);
    }

    /**
     * @param string $IdentifierTypeCode
     */
    public function setIdentifierTypeCode(string $IdentifierTypeCode): void
    {
        $this->setElementValue(5, $IdentifierTypeCode);
    }

    /**
     * @return string
     */
    public function getAssigningFacility(): string
    {
        return $this->getElementValue(6);
    }

    /**
     * @param string $AssigningFacility
     */
    public function setAssigningFacility(string $AssigningFacility): void
    {
        $this->setElementValue(6, $AssigningFacility);
    }

    /**
     * @return string
     */
    public function getEffectiveDate(): string
    {
        return $this->getElementValue(7);
    }

    /**
     * @param string $EffectiveDate
     */
    public function setEffectiveDate(string $EffectiveDate): void
    {
        $this->setElementValue(7, $EffectiveDate);
    }

    /**
     * @return string
     */
    public function getExpirationDate(): string
    {
        return $this->getElementValue(8);
    }

    /**
     * @param string $ExpirationDate
     */
    public function setExpirationDate(string $ExpirationDate): void
    {
        $this->setElementValue(8, $ExpirationDate);
    }

    /**
     * @return string
     */
    public function getAssigningJurisdiction(): string
    {
        return $this->getElementValue(9);
    }

    /**
     * @param string $AssigningJurisdiction
     */
    public function setAssigningJurisdiction(string $AssigningJurisdiction): void
    {
        $this->setElementValue(9, $AssigningJurisdiction);
    }

    /**
     * @return string
     */
    public function getAssigningAgencyOrDepartment(): string
    {
        return $this->getElementValue(10);
    }

    /**
     * @param string $AssigningAgencyOrDepartment
     */
    public function setAssigningAgencyOrDepartment(string $AssigningAgencyOrDepartment): void
    {
        $this->setElementValue(10, $AssigningAgencyOrDepartment);
    }


    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}