<?php


namespace amin0x\nabidh;


final class JCC extends Element
{
    private $JobCode;
    private $JobClass;
    private $JobDescriptionText;

    public function __construct()
    {
    }

    /**
     * @return mixed
     */
    public function getJobCode()
    {
        return $this->JobCode;
    }

    /**
     * @param mixed $JobCode
     */
    public function setJobCode($JobCode): void
    {
        $this->JobCode = $JobCode;
    }

    /**
     * @return mixed
     */
    public function getJobClass()
    {
        return $this->JobClass;
    }

    /**
     * @param mixed $JobClass
     */
    public function setJobClass($JobClass): void
    {
        $this->JobClass = $JobClass;
    }

    /**
     * @return mixed
     */
    public function getJobDescriptionText()
    {
        return $this->JobDescriptionText;
    }

    /**
     * @param mixed $JobDescriptionText
     */
    public function setJobDescriptionText($JobDescriptionText): void
    {
        $this->JobDescriptionText = $JobDescriptionText;
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}