<?php


namespace amin0x\nabidh;


class PRL extends Field
{
    public function __construct($Identifier = '', $Subidentifier = '', $ValueDescriptor = '')
    {
    }

    public function getParentObservationIdentifier(){
        return $this->getElementValue(1);
    }

    public function setParentObservationIdentifier(string $val){
        $this->setElementValue( 1, $val);
    }

    public function getParentObservationSubidentifier(){
        return $this->getElementValue(2);
    }

    public function setParentObservationSubidentifier(string $val){
        $this->setElementValue(2, $val);
    }

    public function getParentObservationValueDescriptor(){
        return $this->getElementValue(3);
    }

    public function setParentObservationValueDescriptor(string $val){
        $this->setElementValue(3, $val);
    }

    public function __toString(): string
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}