<?php
namespace amin0x\nabidh;

class EthnicGroup {
    public const Whitepeople = ['WHI', 'Whitepeople'];
    public const AfricanAmericans = ['AFR', 'AfricanAmericans'];
    public const Jewishpeople = ['JEW', 'Jewishpeople'];
    public const Americans = ['AME', 'Americans'];
    public const AlaskaNatives = ['ALA', 'AlaskaNatives'];
    public const Romanipeople = ['RMP', 'Romanipeople'];
    public const AmericanIndiangroup = ['AMI', 'AmericanIndiangroup'];
    public const Irishpeople = ['IRP', 'Irishpeople'];
    public const NativeHawaiians = ['NAT', 'NativeHawaiians'];
    public const IrishTravellers = ['IRI', 'IrishTravellers'];
    public const BritishBangladeshi = ['BRI', 'BritishBangladeshi'];
    public const HanChinese = ['HAN', 'HanChinese'];
    public const Turkicpeoples = ['TUR', 'Turkicpeoples'];
    public const Mexicans = ['MEX', 'Mexicans'];
    public const Asianpeople = ['ASI', 'Asianpeople'];
    public const Uyghurs = ['UYG', 'Uyghurs'];
    public const PuertoRicans = ['PUE', 'PuertoRicans'];
    public const Kurds = ['KUR', 'Kurds'];
    public const IndigenousPeoplesAmericas = ['IPA', 'IndigenousPeoplesAmericas'];
    public const Bangladeshi = ['BAN', 'Bangladeshi'];
    public const Koreans = ['KOR', 'Koreans'];
    public const Berbers = ['BER', 'Berbers'];
    public const Pashtun = ['PAS', 'Pashtun'];
    public const Circassians = ['CIR', 'Circassians'];
    public const Pamiris = ['PAM', 'Pamiris'];
    public const AssyrianPeople = ['ASS', 'AssyrianPeople'];
    public const Armenians = ['ARM', 'Armenians'];
    public const BalochPeople = ['BAL', 'BalochPeople'];
    public const Palestinians = ['PAL', 'Palestinians'];
    public const Mongols = ['MON', 'Mongols'];
    public const IndoAryanPeoples = ['MON', 'IndoAryanPeoples'];
    public const Hazaras = ['IND', 'Hazaras'];
    public const Uzbeks = ['HAZ', 'Uzbeks'];
    public const Albanians = ['UZB', 'Albanians'];
    public const Arabs = ['ALB', 'Arabs'];
    public const Sindhis = ['ARA', 'Sindhis'];
    public const HmongPeople = ['SIN', 'HmongPeople'];
    public const Kazakhs = ['HMO', 'Kazakhs'];
    public const DravidianPeoples = ['KAZ', 'DravidianPeoples'];
    public const TibetanPeople = ['DRA', 'TibetanPeople'];
    public const AmisPeople = ['TIB', 'AmisPeople'];
    public const Lezgins = ['AMS', 'Lezgins'];
    public const Fijians = ['LEZ', 'Fijians'];
    public const Tatars = ['FIJ', 'Tatars'];
    public const Buryats = ['TAT', 'Buryats'];
    public const Yazidis = ['BUR', 'Yazidis'];
    public const Mestizo = ['YAZ', 'Mestizo'];
    public const LebanesePeople = ['MES', 'LebanesePeople'];
    public const Tajiks = ['LEB', 'Tajiks'];
    public const YaoPeople = ['YAO', 'YaoPeople'];
    public const Romanians = ['ROM', 'Romanians'];
    public const Unknown = ['UNK', 'Unknown'];
}